### ISSUE TITLE
Subir a servidor

### ISSUE THREAD

**Issue by ernesto-butto** [laslorma/article-indexer#5]
Mysql Port: 6604, user: root, password: (empty)
Elastic search link: http://indexer.catwizard.io:9200/, http://45.79.1.250:9200/
> PR: 
> Time: 6h
> Docs: http://docs.lingostand.com/devops_dev_article_indexer.html

- [x] Build enviroment
- [x] Deploy
- [x] Doc: http://docs.lingostand.com/devops_dev_article_indexer.html

Backend: http://indexer.catwizard.io:8085/, http://45.79.1.250:8085
Rebuild Indexer
```
cd /home/development/github/article-indexer && git pull && ./mvnw package -Pprod verify jib:dockerBuild
```
Run Indexer and see logs
```
docker-compose -f ~/docker/docker-compose-files/article-indexer/app.yml up -d && docker logs article-indexer_indexer-app_1 -f
```

## Alias Summary
```
alias rebuildIndexer='cd /home/development/github/article-indexer && git pull && ./mvnw package -Pprod verify jib:dockerBuild'

alias logsIndexer='docker logs article-indexer_indexer-app_1 -f'

alias startIndexerAndSeeLog='docker-compose -f ~/docker/docker-compose-files/article-indexer/app.yml up -d && docker logs article-indexer_indexer-app_1 -f'
alias stopIndexer='docker-compose -f ~/docker/docker-compose-files/article-indexer/app.yml stop'
```

Name of the dockers
```
article-indexer_indexer-app_1           
article-indexer_indexer-mysql_1         
article-indexer_indexer-elasticsearch_1
```

**Comment by ernesto-butto** [comment]
https://www.jhipster.tech/docker-compose/

```
cd /home/development/github/article-indexer

git pull && ./mvnw package -Pprod verify jib:dockerBuild

```
Output
```
[INFO]
[INFO] Containerizing application to Docker daemon as indexer...
[INFO] The base image requires auth. Trying again for adoptopenjdk:11-jre-hotspot...
[INFO]
[INFO] Container entrypoint set to [bash, -c, chmod +x /entrypoint.sh && sync && /entrypoint.sh]
[INFO]
[INFO] Built image to Docker daemon as indexer
[INFO] Executing tasks:
[INFO] [==============================] 100.0% complete
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  06:44 min
[INFO] Finished at: 2019-11-30T20:24:44+01:00
[INFO] -------------------------------------------------------
```
Image built! check by
```
development@lingoProduction:~/github/article-indexer$ docker images
REPOSITORY                            TAG                 IMAGE ID            CREATED             SIZE
indexer                               latest              c20801f43c36        10 hours ago        381MB
```

**Comment by ernesto-butto** [comment]
## Persitence of data: Mysql and ElasticSearch

```
development@lingoProduction:~/docker/docker-compose-files/article-indexer$ cat elasticsearch.yml
version: '2'
services:
  indexer-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    volumes:
      - ~/volumes/jhipster/indexer/elasticsearch/:/usr/share/elasticsearch/data/
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - 'ES_JAVA_OPTS=-Xms1024m -Xmx1024m'
      - 'discovery.type=single-node'
development@lingoProduction:~/docker/docker-compose-files/article-indexer$ cat mysql.yml
version: '2'
services:
  indexer-mysql:
    image: mysql:8.0.17
    volumes:
      - ~/volumes/jhipster/indexer/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=indexer
    ports:
      - 6604:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
```
